# Options for compiling EMMA programs for SGI (IRIX 5.x).
# Distribution version.

RANLIB      = 
MEX_EXT     = mexsg
CMEX_LIBS   = -lemma $(MINCLIBS) -lm -lc
XDR_LIB     = 
CC          = cc

# Options for the MIPS C compiler.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CFLAGS_MEX  = -O2 -prototypes
CFLAGS_STD  = -O2 -prototypes
