# Options for MAC OS 10.3.2
RANLIB      = ranlib
MEX_EXT     = mexmac
CMEX_LIBS   = -lemma $(MINCLIBS) -lm -lc
XDR_LIB     = 
CC          = gcc

# Options for gcc.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CFLAGS_MEX  = -O2 
CFLAGS_STD  = -O2
