#
# Makefile macros needed to put together an EMMA distribution.
#
# $Id: Makefile.version,v 1.7 2010-02-05 04:50:58 claude Exp $
#

# version number, release directory, and release archive file
PACKAGE = emma
VERSION = 1.0.0
RELEASE = $(PACKAGE)-$(VERSION)
ARCHIVE = $(RELEASE).tar.gz

# RCS stuff -- don't forget to change VERSION_SYM with VERSION!
VERSION_SYM = 1_0_0
NAME_SYM = $(PACKAGE)_v$(VERSION_SYM)
STATE = Rel
