
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD*diagnosis_3_bl+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/icbm_segmented_masked_jackmask_res_8mm_blur_050.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, {'PTGENDER', 'APOE_bin'}, '');


[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~diag_3bl+PTGENDER+APOE_bin+Age_bl' ...
    , '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles'}, {'PTGENDER', 'APOE_bin', 'diag_3bl'}, '');


[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''CN'')');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCD, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_AT_CN.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);

[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''MCI'')');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCD, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_AT_MCI.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);

[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''ZAD'')');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCD, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_AT_ZAD.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);


%pick
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD*diag_3bl_analysis+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin', 'diag_3bl_analysis'}, '');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCD, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_atCN_GroupDAnalysis.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCDdiag_3bl_2, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_CNvsMCI.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCDdiag_3bl_3, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_CNvsAD.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);


%cmfisher
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD*PTAU_Pos+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin', 'PTAU_Pos'}, 'strcmp(mdt.diagnosis_3_bl, ''CN'')');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCDPTAU_Pos_1, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_CN_PTAUPosVsNeg.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);



%broca
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD*PTAU_Pos+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin', 'PTAU_Pos'}, 'strcmp(mdt.diagnosis_3_bl, ''MCI'')');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCDPTAU_Pos_1, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Av45_EffectONHypo_MCI_PTAUPosVsNeg.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);




[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsLM('HypometabolismRate_noPVCD_MINCFiles~Av45_bl_Minc_noPVCD*PTAU_Pos+PTGENDER+APOE_bin+Age_bl+Fdg_bl_Minc_noPVCD', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU2_forerroraccidentalrun.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'HypometabolismRate_noPVCD_MINCFiles','Av45_bl_Minc_noPVCD', 'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin', 'PTAU_Pos'}, 'strcmp(mdt.diagnosis_3_bl, ''ZAD'')');
%Not enough subjects for analysis





%%%% GLM Test
%AV45
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsGLM('Conversion~Av45_bl_Minc_noPVCD+PTGENDER+APOE_bin+Age_bl', ...
    'binomial', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'Av45_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''MCI'')');
VoxelStatsWrite(c_struct.tValues.Av45_bl_Minc_noPVCD, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Conversion_byBLAV45_Binomial.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);
%FDG 
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsGLM('Conversion~Fdg_bl_Minc_noPVCD+PTGENDER+APOE_bin+Age_bl', ...
    'binomial', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''MCI'')');
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsGLM('Conversion~Fdg_bl_Minc_noPVCD+PTGENDER+APOE_bin+Age_bl', ...
    'binomial', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'Fdg_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''MCI'')', containers.Map('Fdg_bl_Minc_noPVCD','*(-1)'));
VoxelStatsWrite(c_struct.tValues.Fdg_bl_Minc_noPVCD, '/data/data03/sulantha/VoxelStatsResults/VoxelStats_Conversion_byBLFDG_Binomial.mnc', ... 
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', 189);

%AV_PTAU
[c_struct, slices, image_height, image_width, var_names] = ...
    VoxelStatsGLM('Conversion~Av45_bl_Minc_noPVCD*PTAU_Pos+PTGENDER+APOE_bin+Age_bl', ...
    'binomial', ...
    '/data/data03/sulantha/LinearModelAnalysis_Apr2015/Filterd_MainTable_PTAU.csv', ...
    '/data/data03/sulantha/quarantine/mni_icbm152_t1_tal_nlin_sym_09a_mask_8mm_blur_mask.mnc', ...
    {'Av45_bl_Minc_noPVCD'}, ...
    {'PTGENDER', 'APOE_bin'}, 'strcmp(mdt.diagnosis_3_bl, ''MCI'')');