# Options for compiling EMMA programs for Linux
# Distribution version.

RANLIB      = 
ifneq ($(findstring x86_64,$(shell uname -m)),)
  MEX_EXT     = mexa64
  MEX_FPIC    = -fPIC
else
  MEX_EXT     = mexglx
  MEX_FPIC    =
endif
CMEX_LIBS   = -lemma $(MINCLIBS) -lm -lc
XDR_LIB     = 
CC          = cc

# Options for GCC compiler.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CFLAGS_MEX  = -O3 -funsigned-char $(MEX_FPIC)
CFLAGS_STD  = -O3 -funsigned-char $(MEX_FPIC)
