# Options for SUN4/Sparc (SunOS)
RANLIB      = ranlib
MEX_EXT     = mex4
CMEX_LIBS   = -lemma $(MINCLIBS) -lm -lc
XDR_LIB     = 
CC          = gcc

# Options for gcc.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CFLAGS_MEX  = -O2
CFLAGS_STD  = -O2
