PROG     = micreateimage
OBJS     = args.o dimensions.o
HEADERS  = micreateimage.h \
	   args.h \
   	   dimensions.h
include ../makefile.std

stupid: stupid.o
	$(CC) $(CFLAGS) stupid.o $(LDFLAGS) -o stupid 
