function VoxelStats()
    f = figure;
    set(0, 'DefaultUIControlFontSize', 14);
    set(0, 'DefaultUIControlFontName', 'Avenir');
    set(f, 'units', 'normalized', 'position', [0.2 0.3 0.75 0.7])
    set(f, 'menubar', 'none', 'numbertitle', 'off', 'name', 'VoxelStats');
    tgroup = uitabgroup('Parent', f, 'Position', [0.05 0.05 0.9 0.6]);

    tab1 = uitab('Parent', tgroup, 'Title', 'LM');
    tab2 = uitab('Parent', tgroup, 'Title', 'GLM');
    tab3 = uitab('Parent', tgroup, 'Title', 'ROC');
    tab4 = uitab('Parent', tgroup, 'Title', 't-Test');
    tab5 = uitab('Parent', tgroup, 'Title', 'Paired t-Test');


    %Main UI Controls
    lblDataFile = uicontrol('Tag', 'lblDataFile','Parent', f, 'Style', 'text', 'String', ...
    'Data File:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.025 0.90 0.1 0.05]) ;
    txtDataFile = uicontrol('Tag', 'txtDataFile','Parent', f, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.15 0.90 0.65 0.05], 'HorizontalAlignment', 'left') ;
    chooseDataFile = uicontrol('Tag', 'chooseDataFile','Parent', f, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.85 0.90 0.125 0.05], 'CallBack', {@chooseFile, txtDataFile}) ;

    lblFilter = uicontrol('Tag', 'lblFilter','Parent', f, 'Style', 'text', 'String', ...
    'Filter String:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.025 0.825 0.1 0.05]) ;
    txtFilter = uicontrol('Tag', 'txtFilter','Parent', f, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.15 0.825 0.65 0.05], ...
    'HorizontalAlignment', 'left') ;

    lblMaskFile = uicontrol('Tag', 'lblMaskFile','Parent', f, 'Style', 'text', 'String', ...
    'Mask File:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.025 0.75 0.1 0.05]) ;
    txtMaskFile = uicontrol('Tag', 'txtMaskFile','Parent', f, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.15 0.75 0.65 0.05], 'HorizontalAlignment', 'left') ;
    chooseMaskFile = uicontrol('Tag', 'chooseMaskFile','Parent', f, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.85 0.75 0.125 0.05], 'CallBack', {@chooseFile, txtMaskFile}) ;

    lblImageType = uicontrol('Tag', 'lblImageType','Parent', f, 'Style', 'text', 'String', ...
    'Image Type:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.025 0.675 0.15 0.05]) ;
    chooseImageType = uicontrol('Tag', 'chooseImageType','Parent', f, 'Style', 'popupmenu', ...
    'String', {'minc','nifti'},'units', 'normalized', 'Position', [0.15 0.675 0.25 0.05]) ;

    %UI controls in Tab1 = LM
    lblModel_lm = uicontrol('Tag', 'lblModel_lm','Parent', tab1, 'Style', 'text', 'String', ...
    'Model String:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.85 0.3 0.09]) ;
    txtModel_lm = uicontrol('Tag', 'txtModel_lm','Parent', tab1, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.85 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblMultVar_lm = uicontrol('Tag', 'lblMultVar_lm','Parent', tab1, 'Style', 'text', 'String', ...
    'Multi-value Vars:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.75 0.3 0.09]) ;
    txtMultVar_lm = uicontrol('Tag', 'txtMultVar_lm','Parent', tab1, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.75 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblCatVar_lm = uicontrol('Tag', 'lblCatVar_lm','Parent', tab1, 'Style', 'text', 'String', ...
    'Categorical Vars:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.65 0.3 0.09]) ;
    txtCatVar_lm = uicontrol('Tag', 'txtCatVar_lm','Parent', tab1, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.65 0.7 0.09], 'HorizontalAlignment', 'left') ;

    chooseMixed_lm = uicontrol('Tag', 'chooseMixed_lm','Parent', tab1, 'Style', 'checkbox', ...
    'String', 'Mixed Model', 'units', 'normalized', 'Position', [0.05 0.55 0.3 0.09]) ;

    runVS_lm = uicontrol('Tag', 'runVS_lm','Parent', tab1, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.75 0.45 0.2 0.1], 'CallBack', {@runVS, 'lm'}) ;

    writePanel_lm = uipanel('Tag', 'writePanel_lm','Parent', tab1, 'units', 'normalized', ...
    'Position', [0.45 0 0.54 0.45], 'Title', 'Write Results', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblEst_lm = uicontrol('Tag', 'lblEst_lm','Parent', writePanel_lm, 'Style', 'text', 'String', ...
    'Estimate:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.75 0.3 0.25]) ;
    chooseEst_lm = uicontrol('Tag', 'chooseEst_lm', 'Parent', writePanel_lm, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.75 0.75 0.25], ...
    'CallBack', {@chooseVariable, 'lm'}) ;

    lblVarName_lm = uicontrol('Tag', 'lblVarName_lm','Parent', writePanel_lm, 'Style', 'text', 'String', ...
    'Variable:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.5 0.3 0.25]) ;
    chooseVarName_lm = uicontrol('Tag', 'chooseVarName_lm', 'Parent', writePanel_lm, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.5 0.75 0.25]) ;
    
    lblTemplate_lm = uicontrol('Tag', 'lblTemplate_lm','Parent', writePanel_lm, 'Style', 'text', 'String', ...
    'Template:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.25 0.3 0.25]) ;
    txtTemplate_lm = uicontrol('Tag', 'txtTemplate_lm','Parent', writePanel_lm, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.21 0.31 0.72 0.2], 'HorizontalAlignment', 'left') ;
    
    chooseTemplate_lm = uicontrol('Tag', 'chooseTemplate_lm', 'Parent', writePanel_lm, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.32 0.05 0.19 0.24], 'CallBack', {@chooseFile, txtTemplate_lm}) ;
 
    writeResult_lm = uicontrol('Tag', 'writeResult_lm', 'Parent', writePanel_lm, 'Style', 'pushbutton', ...
    'String', 'Save','units', 'normalized', 'Position', [0.75 0.05 0.19 0.24], 'CallBack', {@saveRes, 'lm'}) ;

    viewResult_lm = uicontrol('Tag', 'viewResult_lm', 'Parent', writePanel_lm, 'Style', 'pushbutton', ...
    'String', 'View','units', 'normalized', 'Position', [0.5 0.05 0.19 0.24], 'CallBack', {@viewRes, 'lm'}) ;

    rftPanel_lm = uipanel('Tag', 'rftPanel_lm','Parent', tab1, 'units', 'normalized', ...
    'Position', [0.01 0 0.43 0.45], 'Title', 'RFT MCC', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblRftSearchVol_lm = uicontrol('Tag', 'lblRftSearchVol_lm','Parent', rftPanel_lm, 'Style', 'text', 'String', ...
    'Search Vol:',  'FontSize', 12,'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.8 0.25 0.2]) ;
    txtRftSearchVol_lm = uicontrol('Tag', 'txtRftSearchVol_lm','Parent', rftPanel_lm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftVoxelNum_lm = uicontrol('Tag', 'lblRftVoxelNum_lm','Parent', rftPanel_lm, 'Style', 'text', 'String', ...
    'Voxel Num:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.59 0.25 0.2]) ;
    txtRftVoxelNum_lm = uicontrol('Tag', 'txtRftVoxelNum_lm','Parent', rftPanel_lm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftFWHM_lm = uicontrol('Tag', 'lblRftFWHM_lm','Parent', rftPanel_lm, 'Style', 'text', 'String', ...
    'FWHM:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.38 0.25 0.2]) ;
    txtRftFWHM_lm = uicontrol('Tag', 'txtRftFWHM_lm','Parent', rftPanel_lm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.38 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftDF_lm = uicontrol('Tag', 'lblRftDF_lm','Parent', rftPanel_lm, 'Style', 'text', 'String', ...
    'DF:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.8 0.15 0.2]) ;
    txtRftDF_lm = uicontrol('Tag', 'txtRftDF_lm','Parent', rftPanel_lm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.72 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftClusterTh_lm = uicontrol('Tag', 'lblRftClusterTh_lm','Parent', rftPanel_lm, 'Style', 'text', 'String', ...
    'Cluster p-val:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.59 0.23 0.2]) ;
    txtRftClusterTh_lm = uicontrol('Tag', 'txtRftClusterTh_lm','Parent', rftPanel_lm, 'Style', 'edit', ...
    'FontSize', 12, 'String', '0.001', 'units', 'normalized', 'Position', [0.72 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    runRFT_lm = uicontrol('Tag', 'runRFT_lm', 'Parent', rftPanel_lm, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.55 0.05 0.42 0.24], 'CallBack', {@runRFT, 'lm'}) ;

    %UI controls in Tab2 = GLM
    lblModel_glm = uicontrol('Tag', 'lblModel_glm', 'Parent', tab2, 'Style', 'text', 'String', ...
    'Model String:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.85 0.3 0.09]) ;
    txtModel_glm = uicontrol('Tag', 'txtModel_glm', 'Parent', tab2, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.85 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblMultVar_glm = uicontrol('Tag', 'lblMultVar_glm', 'Parent', tab2, 'Style', 'text', 'String', ...
    'Multi-value Vars:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.75 0.3 0.09]) ;
    txtMultVar_glm = uicontrol('Tag', 'txtMultVar_glm', 'Parent', tab2, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.75 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblCatVar_glm = uicontrol('Tag', 'lblCatVar_glm', 'Parent', tab2, 'Style', 'text', 'String', ...
    'Categorical Vars:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.65 0.3 0.09]) ;
    txtCatVar_glm = uicontrol('Tag', 'txtCatVar_glm', 'Parent', tab2, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.65 0.7 0.09], 'HorizontalAlignment', 'left') ;

    chooseMixed_glm = uicontrol('Tag', 'chooseMixed_glm', 'Parent', tab2, 'Style', 'checkbox', ...
    'String', 'Mixed Model', 'units', 'normalized', 'Position', [0.05 0.55 0.3 0.09]) ;

    lblDist_glm = uicontrol('Tag', 'lblDist_glm', 'Parent', tab2, 'Style', 'text', 'String', ...
    'Distribution:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.5 0.55 0.2 0.09]) ;
    chooseDist_glm = uicontrol('Tag', 'chooseDist_glm', 'Parent', tab2, 'Style', 'popupmenu', ...
    'String', {'binomial','poisson', 'gamma', 'inverse gaussian'}, 'units', 'normalized', 'Position', [0.65 0.55 0.305 0.09]) ;

    runVS_glm = uicontrol('Tag', 'runVS_glm', 'Parent', tab2, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.75 0.45 0.2 0.1], 'CallBack', {@runVS, 'glm'}) ;

     writePanel_glm = uipanel('Tag', 'writePanel_glm','Parent', tab2, 'units', 'normalized', ...
    'Position', [0.45 0 0.54 0.45], 'Title', 'Write Results', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblEst_glm = uicontrol('Tag', 'lblEst_glm','Parent', writePanel_glm, 'Style', 'text', 'String', ...
    'Estimate:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.75 0.3 0.25]) ;
    chooseEst_glm = uicontrol('Tag', 'chooseEst_glm', 'Parent', writePanel_glm, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.75 0.75 0.25], ...
    'CallBack', {@chooseVariable, 'lm'}) ;

    lblVarName_glm = uicontrol('Tag', 'lblVarName_glm','Parent', writePanel_glm, 'Style', 'text', 'String', ...
    'Variable:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.5 0.3 0.25]) ;
    chooseVarName_glm = uicontrol('Tag', 'chooseVarName_glm', 'Parent', writePanel_glm, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.5 0.75 0.25]) ;
 
    lblTemplate_glm = uicontrol('Tag', 'lblTemplate_glm','Parent', writePanel_glm, 'Style', 'text', 'String', ...
    'Template:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.25 0.3 0.25]) ;
    txtTemplate_glm = uicontrol('Tag', 'txtTemplate_glm','Parent', writePanel_glm, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.21 0.31 0.72 0.2], 'HorizontalAlignment', 'left') ;
    
    chooseTemplate_glm = uicontrol('Tag', 'chooseTemplate_glm', 'Parent', writePanel_glm, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.32 0.05 0.19 0.24], 'CallBack', {@chooseFile, txtTemplate_glm}) ;
 
    writeResult_glm = uicontrol('Tag', 'writeResult_glm', 'Parent', writePanel_glm, 'Style', 'pushbutton', ...
    'String', 'Save','units', 'normalized', 'Position', [0.75 0.05 0.19 0.24], 'CallBack', {@saveRes, 'glm'}) ;

    viewResult_glm = uicontrol('Tag', 'viewResult_glm', 'Parent', writePanel_glm, 'Style', 'pushbutton', ...
    'String', 'View','units', 'normalized', 'Position', [0.5 0.05 0.19 0.24], 'CallBack', {@viewRes, 'glm'}) ;

    rftPanel_glm = uipanel('Tag', 'rftPanel_glm','Parent', tab2, 'units', 'normalized', ...
    'Position', [0.01 0 0.43 0.45], 'Title', 'RFT MCC', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblRftSearchVol_glm = uicontrol('Tag', 'lblRftSearchVol_glm','Parent', rftPanel_glm, 'Style', 'text', 'String', ...
    'Search Vol:',  'FontSize', 12,'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.8 0.25 0.2]) ;
    txtRftSearchVol_glm = uicontrol('Tag', 'txtRftSearchVol_glm','Parent', rftPanel_glm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftVoxelNum_glm = uicontrol('Tag', 'lblRftVoxelNum_glm','Parent', rftPanel_glm, 'Style', 'text', 'String', ...
    'Voxel Num:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.59 0.25 0.2]) ;
    txtRftVoxelNum_glm = uicontrol('Tag', 'txtRftVoxelNum_glm','Parent', rftPanel_glm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftFWHM_glm = uicontrol('Tag', 'lblRftFWHM_glm','Parent', rftPanel_glm, 'Style', 'text', 'String', ...
    'FWHM:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.38 0.25 0.2]) ;
    txtRftFWHM_glm = uicontrol('Tag', 'txtRftFWHM_glm','Parent', rftPanel_glm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.38 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftDF_glm = uicontrol('Tag', 'lblRftDF_glm','Parent', rftPanel_glm, 'Style', 'text', 'String', ...
    'DF:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.8 0.15 0.2]) ;
    txtRftDF_glm = uicontrol('Tag', 'txtRftDF_glm','Parent', rftPanel_glm, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.72 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftClusterTh_glm = uicontrol('Tag', 'lblRftClusterTh_glm','Parent', rftPanel_glm, 'Style', 'text', 'String', ...
    'Cluster p-val:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.59 0.23 0.2]) ;
    txtRftClusterTh_glm = uicontrol('Tag', 'txtRftClusterTh_glm','Parent', rftPanel_glm, 'Style', 'edit', ...
    'FontSize', 12, 'String', '0.001', 'units', 'normalized', 'Position', [0.72 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    runRFT_glm = uicontrol('Tag', 'runRFT_glm', 'Parent', rftPanel_glm, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.55 0.05 0.42 0.24], 'CallBack', {@runRFT, 'glm'}) ;


    %UI controls in Tab3 = ROC
    lblDataCol_roc = uicontrol('Tag', 'lblDataCol_roc','Parent', tab3, 'Style', 'text', 'String', ...
    'Image Column:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.85 0.3 0.09]) ;
    txtDataCol_roc = uicontrol('Tag', 'txtDataCol_roc','Parent', tab3, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.85 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblGroupCol_roc = uicontrol('Tag', 'lblGroupCol_roc','Parent', tab3, 'Style', 'text', 'String', ...
    'Grouping Column:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.75 0.3 0.09]) ;
    txtGroupCol_roc = uicontrol('Tag', 'txtGroupCol_roc','Parent', tab3, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.75 0.7 0.09], 'HorizontalAlignment', 'left') ;

    runVS_roc = uicontrol('Tag', 'runVS_roc','Parent', tab3, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.75 0.45 0.2 0.1], 'CallBack', {@runVS, 'roc'}) ;

    writePanel_roc = uipanel('Tag', 'writePanel_roc','Parent', tab3, 'units', 'normalized', ...
    'Position', [0.45 0 0.54 0.45], 'Title', 'Write Results', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblEst_roc = uicontrol('Tag', 'lblEst_roc','Parent', writePanel_roc, 'Style', 'text', 'String', ...
    'Estimate:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.75 0.3 0.25]) ;
    chooseEst_roc = uicontrol('Tag', 'chooseEst_roc', 'Parent', writePanel_roc, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.75 0.75 0.25], ...
    'CallBack', {@chooseVariable, 'roc'}) ;

    lblTemplate_roc = uicontrol('Tag', 'lblTemplate_roc','Parent', writePanel_roc, 'Style', 'text', 'String', ...
    'Template:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.25 0.3 0.25]) ;
    txtTemplate_roc = uicontrol('Tag', 'txtTemplate_roc','Parent', writePanel_roc, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.21 0.31 0.72 0.2], 'HorizontalAlignment', 'left') ;
    
    chooseTemplate_roc = uicontrol('Tag', 'chooseTemplate_roc', 'Parent', writePanel_roc, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.32 0.05 0.19 0.24], 'CallBack', {@chooseFile, txtTemplate_roc}) ;
 
    writeResult_roc = uicontrol('Tag', 'writeResult_roc', 'Parent', writePanel_roc, 'Style', 'pushbutton', ...
    'String', 'Save','units', 'normalized', 'Position', [0.75 0.05 0.19 0.24], 'CallBack', {@saveRes, 'roc'}) ;

    viewResult_roc = uicontrol('Tag', 'viewResult_roc', 'Parent', writePanel_roc, 'Style', 'pushbutton', ...
    'String', 'View','units', 'normalized', 'Position', [0.5 0.05 0.19 0.24], 'CallBack', {@viewRes, 'roc'}) ;
 
    %UI controls for tab4 - T
    lblDataCol_t = uicontrol('Tag', 'lblDataCol_t','Parent', tab4, 'Style', 'text', 'String', ...
    'Image Column:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.85 0.3 0.09]) ;
    txtDataCol_t = uicontrol('Tag', 'txtDataCol_t','Parent', tab4, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.85 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblGroupCol_t = uicontrol('Tag', 'lblGroupCol_t','Parent', tab4, 'Style', 'text', 'String', ...
    'Grouping Column:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.75 0.3 0.09]) ;
    txtGroupCol_t = uicontrol('Tag', 'txtGroupCol_t','Parent', tab4, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.75 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblGroup1_t = uicontrol('Tag', 'lblGroup1_t', 'Parent', tab4, 'Style', 'text', 'String', ...
    'Group 1:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.65 0.3 0.09]) ;
    txtGroup1_t = uicontrol('Tag', 'txtGroup1_t', 'Parent', tab4, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.65 0.2 0.09], 'HorizontalAlignment', 'left') ;
    
    lblGroup2_t = uicontrol('Tag', 'lblGroup2_t', 'Parent', tab4, 'Style', 'text', 'String', ...
    'Group 2:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.5 0.65 0.3 0.09]) ;
    txtGroup2_t = uicontrol('Tag', 'txtGroup2_t', 'Parent', tab4, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.60 0.65 0.2 0.09], 'HorizontalAlignment', 'left') ;

    runVS_t = uicontrol('Tag', 'runVS_t','Parent', tab4, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.75 0.45 0.2 0.1], 'CallBack', {@runVS, 't'}) ;

    writePanel_t = uipanel('Tag', 'writePanel_t','Parent', tab4, 'units', 'normalized', ...
    'Position', [0.45 0 0.54 0.45], 'Title', 'Write Results', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblEst_t = uicontrol('Tag', 'lblEst_t','Parent', writePanel_t, 'Style', 'text', 'String', ...
    'Estimate:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.75 0.3 0.25]) ;
    chooseEst_t = uicontrol('Tag', 'chooseEst_t', 'Parent', writePanel_t, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.75 0.75 0.25], ...
    'CallBack', {@chooseVariable, 't'}) ;

    lblTemplate_t = uicontrol('Tag', 'lblTemplate_t','Parent', writePanel_t, 'Style', 'text', 'String', ...
    'Template:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.25 0.3 0.25]) ;
    txtTemplate_t = uicontrol('Tag', 'txtTemplate_t','Parent', writePanel_t, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.21 0.31 0.72 0.2], 'HorizontalAlignment', 'left') ;
    
    chooseTemplate_t = uicontrol('Tag', 'chooseTemplate_t', 'Parent', writePanel_t, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.32 0.05 0.19 0.24], 'CallBack', {@chooseFile, txtTemplate_t}) ;
 
    writeResult_t = uicontrol('Tag', 'writeResult_t', 'Parent', writePanel_t, 'Style', 'pushbutton', ...
    'String', 'Save','units', 'normalized', 'Position', [0.75 0.05 0.19 0.24], 'CallBack', {@saveRes, 't'}) ;

    viewResult_t = uicontrol('Tag', 'viewResult_t', 'Parent', writePanel_t, 'Style', 'pushbutton', ...
    'String', 'View','units', 'normalized', 'Position', [0.5 0.05 0.19 0.24], 'CallBack', {@viewRes, 't'}) ;

    rftPanel_t = uipanel('Tag', 'rftPanel_t','Parent', tab4, 'units', 'normalized', ...
    'Position', [0.01 0 0.43 0.45], 'Title', 'RFT MCC', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblRftSearchVol_t = uicontrol('Tag', 'lblRftSearchVol_t','Parent', rftPanel_t, 'Style', 'text', 'String', ...
    'Search Vol:',  'FontSize', 12,'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.8 0.25 0.2]) ;
    txtRftSearchVol_t = uicontrol('Tag', 'txtRftSearchVol_t','Parent', rftPanel_t, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftVoxelNum_t = uicontrol('Tag', 'lblRftVoxelNum_t','Parent', rftPanel_t, 'Style', 'text', 'String', ...
    'Voxel Num:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.59 0.25 0.2]) ;
    txtRftVoxelNum_t = uicontrol('Tag', 'txtRftVoxelNum_t','Parent', rftPanel_t, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftFWHM_t = uicontrol('Tag', 'lblRftFWHM_t','Parent', rftPanel_t, 'Style', 'text', 'String', ...
    'FWHM:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.38 0.25 0.2]) ;
    txtRftFWHM_t = uicontrol('Tag', 'txtRftFWHM_t','Parent', rftPanel_t, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.38 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftDF_t = uicontrol('Tag', 'lblRftDF_t','Parent', rftPanel_t, 'Style', 'text', 'String', ...
    'DF:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.8 0.15 0.2]) ;
    txtRftDF_t = uicontrol('Tag', 'txtRftDF_t','Parent', rftPanel_t, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.72 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftClusterTh_t = uicontrol('Tag', 'lblRftClusterTh_t','Parent', rftPanel_t, 'Style', 'text', 'String', ...
    'Cluster p-val:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.59 0.23 0.2]) ;
    txtRftClusterTh_t = uicontrol('Tag', 'txtRftClusterTh_t','Parent', rftPanel_t, 'Style', 'edit', ...
    'FontSize', 12, 'String', '0.001', 'units', 'normalized', 'Position', [0.72 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    runRFT_t = uicontrol('Tag', 'runRFT_t', 'Parent', rftPanel_t, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.55 0.05 0.42 0.24], 'CallBack', {@runRFT, 't'}) ;

    %UI controls for tab5 - PairedT
    lblContrastCol1_pt = uicontrol('Tag', 'lblContrastCol1_pt','Parent', tab5, 'Style', 'text', 'String', ...
    'Contrast Column 1:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.85 0.3 0.09]) ;
    txtContrastCol1_pt = uicontrol('Tag', 'txtContrastCol1_pt','Parent', tab5, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.85 0.7 0.09], 'HorizontalAlignment', 'left') ;

    lblContrastCol2_pt = uicontrol('Tag', 'lblContrastCol2_pt','Parent', tab5, 'Style', 'text', 'String', ...
    'Contrast Column 2:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.05 0.75 0.3 0.09]) ;
    txtContrastCol2_pt = uicontrol('Tag', 'txtContrastCol2_pt','Parent', tab5, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.25 0.75 0.7 0.09], 'HorizontalAlignment', 'left') ;

    runVS_pt = uicontrol('Tag', 'runVS_pt','Parent', tab5, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.75 0.45 0.2 0.1], 'CallBack', {@runVS, 'pt'}) ;

    writePanel_pt = uipanel('Tag', 'writePanel_pt','Parent', tab5, 'units', 'normalized', ...
    'Position', [0.45 0 0.54 0.45], 'Title', 'Write Results', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblEst_pt = uicontrol('Tag', 'lblEst_pt','Parent', writePanel_pt, 'Style', 'text', 'String', ...
    'Estimate:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.75 0.3 0.25]) ;
    chooseEst_pt = uicontrol('Tag', 'chooseEst_pt', 'Parent', writePanel_pt, 'Style', 'popupmenu', ...
     'String', {''}, 'units', 'normalized', 'Position', [0.2 0.75 0.75 0.25], ...
    'CallBack', {@chooseVariable, 'pt'}) ;

    lblTemplate_pt = uicontrol('Tag', 'lblTemplate_pt','Parent', writePanel_pt, 'Style', 'text', 'String', ...
    'Template:', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.25 0.3 0.25]) ;
    txtTemplate_pt = uicontrol('Tag', 'txtTemplate_pt','Parent', writePanel_pt, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.21 0.31 0.72 0.2], 'HorizontalAlignment', 'left') ;
    
    chooseTemplate_pt = uicontrol('Tag', 'chooseTemplate_pt', 'Parent', writePanel_pt, 'Style', 'pushbutton', ...
    'String', 'Browse','units', 'normalized', 'Position', [0.32 0.05 0.19 0.24], 'CallBack', {@chooseFile, txtTemplate_pt}) ;
 
    writeResult_pt = uicontrol('Tag', 'writeResult_pt', 'Parent', writePanel_pt, 'Style', 'pushbutton', ...
    'String', 'Save','units', 'normalized', 'Position', [0.75 0.05 0.19 0.24], 'CallBack', {@saveRes, 'pt'}) ;

    viewResult_pt = uicontrol('Tag', 'viewResult_pt', 'Parent', writePanel_pt, 'Style', 'pushbutton', ...
    'String', 'View','units', 'normalized', 'Position', [0.5 0.05 0.19 0.24], 'CallBack', {@viewRes, 'pt'}) ;

    rftPanel_pt = uipanel('Tag', 'rftPanel_pt','Parent', tab5, 'units', 'normalized', ...
    'Position', [0.01 0 0.43 0.45], 'Title', 'RFT MCC', ...
    'FontSize',14, 'FontName', 'Avenir');
    
    lblRftSearchVol_pt = uicontrol('Tag', 'lblRftSearchVol_pt','Parent', rftPanel_pt, 'Style', 'text', 'String', ...
    'Search Vol:',  'FontSize', 12,'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.8 0.25 0.2]) ;
    txtRftSearchVol_pt = uicontrol('Tag', 'txtRftSearchVol_pt','Parent', rftPanel_pt, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftVoxelNum_pt = uicontrol('Tag', 'lblRftVoxelNum_pt','Parent', rftPanel_pt, 'Style', 'text', 'String', ...
    'Voxel Num:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.59 0.25 0.2]) ;
    txtRftVoxelNum_pt = uicontrol('Tag', 'txtRftVoxelNum_pt','Parent', rftPanel_pt, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftFWHM_pt = uicontrol('Tag', 'lblRftFWHM_pt','Parent', rftPanel_pt, 'Style', 'text', 'String', ...
    'FWHM:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.38 0.25 0.2]) ;
    txtRftFWHM_pt = uicontrol('Tag', 'txtRftFWHM_pt','Parent', rftPanel_pt, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.23 0.38 0.25 0.2], 'HorizontalAlignment', 'left') ;

    lblRftDF_pt = uicontrol('Tag', 'lblRftDF_pt','Parent', rftPanel_pt, 'Style', 'text', 'String', ...
    'DF:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.8 0.15 0.2]) ;
    txtRftDF_pt = uicontrol('Tag', 'txtRftDF_pt','Parent', rftPanel_pt, 'Style', 'edit', ...
    'FontSize', 12, 'units', 'normalized', 'Position', [0.72 0.8 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    lblRftClusterTh_pt = uicontrol('Tag', 'lblRftClusterTh_pt','Parent', rftPanel_pt, 'Style', 'text', 'String', ...
    'Cluster p-val:', 'FontSize', 12, 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.49 0.59 0.23 0.2]) ;
    txtRftClusterTh_pt = uicontrol('Tag', 'txtRftClusterTh_pt','Parent', rftPanel_pt, 'Style', 'edit', ...
    'FontSize', 12, 'String', '0.001', 'units', 'normalized', 'Position', [0.72 0.59 0.25 0.2], 'HorizontalAlignment', 'left') ;
    
    runRFT_pt = uicontrol('Tag', 'runRFT_pt', 'Parent', rftPanel_pt, 'Style', 'pushbutton', ...
    'String', 'Run','units', 'normalized', 'Position', [0.55 0.05 0.42 0.24], 'CallBack', {@runRFT, 'pt'}) ;

    
    lblStatus = uicontrol('Tag', 'lblStatus','Parent', f, 'Style', 'text', 'String', ...
    'VoxelStats v1.1 - Idle', 'HorizontalAlignment', 'left', 'units', 'normalized', 'Position', [0.01 0.0 0.4 0.05]) ;
   
    handles = guihandles(f);
    guidata(f, handles)
end